service: pycon-demo

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  profile: pycon2021-demo
  region: ap-northeast-2
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET
  excel:
    handler: handler.pycon
    events:
      - http:
          path: excel
          method: GET
