service: pycon2021

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  profile: pycon2021
  lambdaHashingVersion: 20201221

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: GET

          